["github.com/blang/semver"]
  sumVersion = "v3.5.1+incompatible"
  ["github.com/blang/semver".fetch]
    type = "git"
    url = "https://github.com/blang/semver"
    rev = "2ee87856327ba09384cabd113bc6b5d174e9ec0f"
    sha256 = "13ws259bwcibkclbr82ilhk6zadm63kxklxhk12wayklj8ghhsmy"

["github.com/goccy/go-json"]
  sumVersion = "v0.7.9"
  ["github.com/goccy/go-json".fetch]
    type = "git"
    url = "https://github.com/goccy/go-json"
    rev = "d1195dff31fd59a147598c6cd2315b72e070188f"
    sha256 = "0s41185s5diacbkvy2vhglzcr6vlw4kvw27nj3kzd8xrx2rqwy7p"

["github.com/valyala/fastjson"]
  sumVersion = "v1.6.3"
  ["github.com/valyala/fastjson".fetch]
    type = "git"
    url = "https://github.com/valyala/fastjson"
    rev = "20830cfb065be07053e7eae99a52d68f214b5962"
    sha256 = "1dacn3m8m0zhzhvxbv3vly2zpbcz0yy3kvshq9ahh4916rs1psgq"

["github.com/vladimirvivien/automi"]
  sumVersion = "v0.1.0-alpha.0.0.20210803044724-6b6f77fbd090"
  ["github.com/vladimirvivien/automi".fetch]
    type = "git"
    url = "https://github.com/vladimirvivien/automi"
    rev = "6b6f77fbd09044aec6ac07dfe3a77f6724838b42"
    sha256 = "0qnr7vyvbp88lab78w1ywmfd9nabwfbyfvdharb0wz06056y4wqq"
